# image:
#   name: docker/compose:latest

# services:
#   - docker:dind

# variables:
#   DOCKER_HOST: tcp://docker:2375/
#   DOCKER_DRIVER: overlay2
#   DOCKER_TLS_CERTDIR: "" 

stages:
  - deploy

deploy:
  image: ruby:2.5
  stage: deploy
  script:
    - cp $DOCKER_COMPOSE docker-compose.yml
    - echo "$STAGE_ID_RSA" > key.pem
    - chmod 400 key.pem
    # stop existing docker container & remove images
    - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "rm -rf smartlab-api || true"
    - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "mkdir smartlab-api || true"
    # - scp -r $PWD/* furqon@10.0.2.7:/home/furqon/smartlab-api
    - scp -i key.pem -o StrictHostKeyChecking=no -r $PWD/* furqon@10.0.2.7:/home/$STAGE_SERVER_USER/smartlab-api
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "cd ./smartlab-api"
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "pwd"
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "ls"
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "cat docker-compose.yml"
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "cat Dockerfile"
    # - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "echo $DOCKER_COMPOSE > docker-compose.yml"
    - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "docker-compose -f /smartlab-api/docker-compose.yml build --no-cache"
    - ssh -i key.pem -o StrictHostKeyChecking=no $STAGE_SERVER_USER@$STAGE_SERVER_IP "docker-compose -f /smartlab-api/docker-compose.yml up -d"

    # - mkdir -p furqon@10.0.2.7:/home/furqon/smartlab-api
    # - scp -r $PWD/* furqon@10.0.2.7:/home/furqon/smartlab-api
    # - cd furqon@10.0.2.7:/home/furqon/smartlab-api
    # - echo "$DOCKER_COMPOSE" > docker-compose.yml
    # - docker image prune -f
    # - docker-compose build --no-cache
    # - docker-compose up -d
    # - pwd
    # - hostname
  #  furqon@10.0.2.7:/home/furqon/smartlab-api
# stages:
#   - deploy

# deploy:
#   # image: docker:18.09-dind
#   image: docker:latest
#   stage: deploy
#   # services:
#   #   - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: "" 
#   script:
#   # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#   # - docker push "$CI_REGISTRY_IMAGE"
#   # Or use docker-compose if you have to build and push multiple images:
#     - apk add --no-cache docker-compose
#     - echo "$DOCKER_COMPOSE" > docker-compose.yml
#     - docker-compose build
#     - docker-compose up -d