image:
  name: docker/compose:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" 

stages:
  - deploy

deploy:
  stage: deploy
  # only:
  #   - production
  script:
    - mkdir -p /home/app/
    - cp -r $PWD/* /home/app/
    - cd /home/app/
    - echo "$DOCKER_COMPOSE" > docker-compose.yml
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
    - pwd
    - hostname
   
# stages:
#   - deploy

# deploy:
#   # image: docker:18.09-dind
#   image: docker:latest
#   stage: deploy
#   # services:
#   #   - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: "" 
#   script:
#   # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#   # - docker push "$CI_REGISTRY_IMAGE"
#   # Or use docker-compose if you have to build and push multiple images:
#     - apk add --no-cache docker-compose
#     - echo "$DOCKER_COMPOSE" > docker-compose.yml
#     - docker-compose build
#     - docker-compose up -d