# image: docker
# services:
#   - docker:dind  
stages:
  - build

build:
  image: docker:18.09-dind
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "" 
  script:
    - apk add --no-cache docker-compose
    - echo "$DOCKER_COMPOSE" > docker-compose.yml
    - docker-compose up -d
   