stages:
  - deploy

deploy:
  # image: docker:18.09-dind
  image: docker:latest
  stage: deploy
  # services:
  #   - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "" 
  script:
  # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  # - docker push "$CI_REGISTRY_IMAGE"
  # Or use docker-compose if you have to build and push multiple images:
    - apk add --no-cache docker-compose
    - echo "$DOCKER_COMPOSE" > docker-compose.yml
    - docker-compose build
    - docker-compose up -d

# stages:
#   - deploy

# deploy:
#   image: docker:18.09-dind
#   stage: deploy
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: "" 
#   script:
#     - apk add --no-cache docker-compose
#     - echo "$DOCKER_COMPOSE" > docker-compose.yml
#     - docker-compose up -d
   